name: test
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master


defaults:
  run:
    shell: bash -l -eo pipefail {0}

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: install mamba
        uses: mamba-org/provision-with-micromamba@v13
        with:
          environment-file: environment-dev.yml
          environment-name: xeus-octave
      - name: Configure
        run: cmake --preset conda-debug-osmesa
      - name: Build
        run: cmake --build --preset conda-debug-osmesa
      - name: Install
        run: cmake --install build/cmake/conda-debug-osmesa
      - name: Test
        run: python -m pytest ./test
