name: test
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master


defaults:
  run:
    shell: bash -l -eo pipefail {0}

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install mamba
        uses: mamba-org/provision-with-micromamba@v13
        with:
          environment-file: environment-dev.yml
          environment-name: xeus-octave
          cache-downloads: true
      - name: Configure
        run: cmake --preset conda-debug-osmesa
      - name: Build
        run: cmake --build --preset conda-debug-osmesa
      - name: Install
        run: cmake --install build/cmake/conda-debug-osmesa
      - name: Test
        run: python -m pytest ./test

  static-analysis:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: Install mamba
        uses: mamba-org/provision-with-micromamba@v13
        with:
          environment-file: environment-dev.yml
          environment-name: xeus-octave
          cache-downloads: true
      - name: Set PYTHON_HASH
        run: echo "PYTHON_HASH=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: precommit-v1-${{ env.PYTHON_HASH }}-${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Pre-commit hooks
        run: python -m pre_commit run --all-files --show-diff-on-failure

  test-doc:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: Install mamba
        uses: mamba-org/provision-with-micromamba@v13
        with:
          environment-file: environment-dev.yml
          environment-name: xeus-octave
          cache-downloads: true
      - name: Build documentation
        run: make -C docs html
      - name: Test documentation links
        run: make -C docs linkcheck
